
SUB_GENRE_MAP = {
    "hip hop":"hip hop",
    "kompa": "afrobeat",
    "deep house": "housentechno",
    "drum and bass": "drum and bass",
    "trap": "trap",
    "jersey club": "housentechno",
    "pop":"chillout",
    "hyperpop":"future bass",
    "rnb":"soul",
    "lo-fi hip hop": "hip hop",
    "flamenco": "flamenco",
    "tech house": "housentechno",
    "jungle": "drum and bass",
    "leftfield bass": "dubstep",
    "trip hop": "trip hop",
    "house": "housentechno",
    "uk garage": "housentechno",
    "disco": "funky",
    "edm": "housentechno",
    "neo soul": "soul",
    "afropop & afrobeats": "afrobeat",
    "techno": "housentechno",
    "future soul": "soul",
    "soul": "soul",
    "future bass": "future bass",
    "cinematic": "cinematic",
    "tropical house": "housentechno",
    "bossa nova": "latin american",
    "synthwave": "chillwave",
    "minimal techno": "housentechno",
    "funk": "funky",
    "latin american": "latin american",
    "reggaeton": "latin american",
    "latin trap": "latin american",
    "psy trance": "housentechno",
    "jazz": "soul",
    "uk drill": "trap",
    "boom bap": "hip hop",
    "glitch": "idm",
    "idm": "idm",
    "experimental": "idm",
    "desert blues": "african",
    "glitch hop": "idm",
    "reggae": "reggaedub",
    "dub": "reggaedub",
    "cumbia": "latin american",
    "afro latin": "latin american",
    "caribbean": "caribbean",
    "jump up dnb": "drum and bass",
    "dubstep": "dubstep",
    "trap edm": "trap",
    "tearout dubstep": "dubstep",
    "asian": "asian",
    "chiptune": "idm",
    "big room house": "housentechno",
    "hard techno": "housentechno",
    "melodic techno": "housentechno",
    "drumstep": "dubstep",
    "downtempo": "chillwave",
    "drill": "trap",
    "indie pop": "chillwave",
    "synth-pop": "chillwave",
    "dancehall": "latin american",
    "son cubano": "latin american",
    "chillout": "chillwave",
    "gospel": "soul",
    "game audio": "idm",
    "future house": "housentechno",
    "progressive house": "housentechno",
    "electro": "housentechno",
    "funky house": "funky",
    "electro house": "housentechno",
    "breakbeat": "drum and bass",
    "ambient": "chillwave",
    "trance": "housentechno",
    "middle eastern": "asian",
    "breaks": "drum and bass",
    "dembow": "latin american",
    "indie electronic": "indie",
    "deep dubstep": "dubstep",
    "indie rock": "indie",
    "afro house": "afrobeats",
    "phonk": "funky",
}